version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitActionsNewProject
  gitServerName: poanTest
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
